package com.ken10.Phase2.OptimizationAlgorithms;

import com.ken10.Phase2.SolarSystemModel.*;
import com.ken10.Phase2.StatesCalculations.EphemerisLoader;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * This class is responsible for determining an optimal launch
 * velocity for a probe based on LaunchData. It uses a two-step optimization
 * process: an initial guess generated by an EvolutionAlgorithm, and refinement with
 *  HillClimbing.
 *
 */
public class OptimalVelocityFinder{
LaunchData launchData;
RK4Probe foundData;


    public OptimalVelocityFinder(LaunchData launchData) {
        this.launchData = launchData;
    }

    public void solve(){
        foundData = findLaunchVelocity();
    }

    public RK4Probe getFoundData(){
        return foundData;
    }
    /**
     * Runs the two-stage optimization to find the best launch velocity.
     *
     * @return A simulated probe with the optimal launch configuration.
     */
    private RK4Probe findLaunchVelocity() {
        EvolutionAlgorithm initialGuess = new EvolutionAlgorithm(launchData);
        initialGuess.solve();
        RK4Probe currentGuess = initialGuess.getEvolutionAlgorithmInitialGuess();
        HillClimbing finalGuess = new HillClimbing(currentGuess, launchData);
        finalGuess.solve();
        return finalGuess.getBestSimulation();
    }

    private static EphemerisLoader findFirstMissionHistory(){
        Vector earthPos = new Vector (-1.4664541859104577E8, -2.8949304626334388E7, 2241.9186033698497);
        Probe probe = new Probe("probe", earthPos, new Vector (63.29024702239812, -33.49000052271595, -15.072908267640539));
        EphemerisLoader eph = new EphemerisLoader(false);
        eph.solve();
        return eph;
    }

    private static LaunchData prepareDataForReturn(EphemerisLoader mission1){
        List<LocalDateTime> sortedTimes = new ArrayList<>(mission1.history.keySet().stream().sorted().toList());
        LocalDateTime startTime2 = sortedTimes.get(sortedTimes.size()-2);
        LocalDateTime endTime2 = LocalDateTime.of(2027, 4, 1, 0,0,0);
        BodyID destination = BodyID.EARTH;
        BodyID launchPlanet = BodyID.TITAN;
        ArrayList<CelestialBodies> initialState = mission1.history.get(startTime2);
        Vector initialPos = initialState.get(BodyID.SPACESHIP.index()).getPosition();
        initialState.remove(BodyID.SPACESHIP.index());
        return new LaunchData(destination, launchPlanet, initialPos, startTime2, endTime2, initialState);
    }

    public static void main(String[] args) {
        EphemerisLoader mission1 = findFirstMissionHistory();
        LaunchData launchData2 = prepareDataForReturn(mission1);
        OptimalVelocityFinder optimalVelocityFinder = new OptimalVelocityFinder(launchData2);
        optimalVelocityFinder.solve();
        System.out.println(optimalVelocityFinder.getFoundData());

    }
}
//----------------------------------------------------------
//Initial probe position and velocity: (-1.4664541859104577E8, -2.8949304626334388E7, 2241.9186033698497) (62.37766685559131, -32.92234163864975, -15.852587264581345)
//Velocity magnitude relative to earth: 59.35185082621291
//Closest Distance to Titan: 2545.9443054973567
//Date of closest approach: 2026-03-17T20:52



//MISSION 1 RESULTS
//----------------------------------------------------------
//Initial probe position and velocity: (-1.4664541859104577E8, -2.8949304626334388E7, 2241.9186033698497) (63.29024702239812, -33.49000052271595, -15.072908267640539)
//Velocity magnitude relative to earth: 60.066056771931656
//Closest Distance to Titan: 2508.27816086085
//Date of closest approach: 2026-03-20T02:26